{
  "name": "FRPC",
  "version": "1.0.0",
  "slug": "frpc",
  "description": "FRP client (frpc) for Home Assistant",
  "arch": ["aarch64", "amd64", "armv7"],
  "startup": "services",
  "boot": "auto",
  "options": {
    "frp_server": "example.com",
    "frp_server_port": 7000,
    "frp_token": "changeme",
    "tunnels": []
  },
  "schema": {
    "frp_server": "str",
    "frp_server_port": "int",
    "frp_token": "str",
    "tunnels": [
      {
        "name": "str",
        "type": "str",
        "local_host": "str",
        "local_port": "int",
        "remote_port": "int?",
        "subdomain": "str?"
      }
    ]
  }
}
